### ISSUE TITLE
Add units to values cards

### ISSUE THREAD

**Issue by amadeuspzs** [DecodedCo/predix-seed-xlp#19]
![image](https://cloud.githubusercontent.com/assets/534681/19169036/a27f5b42-8be0-11e6-8803-1c80f3599710.png)

We need the user to specify units e.g. `MW` `m/s` etc.

**Comment by jaclynadams** [comment]
Isn't that part of the title? Because that is already designed for customizing.

**Comment by amadeuspzs** [comment]
You're absolutely right! :)
