### ISSUE TITLE
Implement alerts for Demand and Output inconsistencies

### ISSUE THREAD

**Issue by amadeuspzs** [DecodedCo/predix-seed-xlp#24]
Can we trigger alerts when demand <> TotalPower?

![image](https://cloud.githubusercontent.com/assets/534681/19170955/6ce9a4bc-8be8-11e6-9c7f-975294fa0a51.png)

Or turn the text color red?

**Comment by jaclynadams** [comment]
Added an alert when demand gets greater than power output.
