### ISSUE TITLE
Timeseries not rescaling

### ISSUE THREAD

**Issue by amadeuspzs** [DecodedCo/predix-seed-xlp#37]
Switching to Temperature keeps previous scale:

![image](https://cloud.githubusercontent.com/assets/534681/19284787/2ac21b60-8fac-11e6-9803-c85c88c3f8aa.png)

**Comment by jaclynadams** [comment]
Don't think this will be an issue anymore now that I am removing the dropdown for tag selection because multiple charts work now and multiple series on a chart.

**Comment by jaclynadams** [comment]
Still always started scale from 0... my last comment was wrong. Set scale to 'dynamic' aka based on data.
