### ISSUE TITLE
Create calculated/static value card (not from API)

### ISSUE THREAD

**Issue by jaclynadams** [DecodedCo/predix-seed-xlp#40]

**Comment by jaclynadams** [comment]
Created a way to pass in a value to a card. Should I add any other features? Passing in multiple values to display, or a demo function or anything? What are some use cases for this? Probably just some kind of calculation on tags that already exist?

**Comment by amadeuspzs** [comment]
Yes the main need is to work out the delta on `demand - power` and display that. Perhaps a function to calculate that?
