### ISSUE TITLE
Split out values into individual cards

### ISSUE THREAD

**Issue by amadeuspzs** [DecodedCo/predix-seed-xlp#7]
Right now values appear all together:

![image](https://cloud.githubusercontent.com/assets/534681/19082703/438a2a9a-8a2d-11e6-806b-5333befe318c.png)
1. Can we split out each value as a separate card
2. Can we allow user to change h1 of card to e.g. "Wind Power (MW)" 
3. Can we add latest timestamp from data, formatted for information (check we have latest data)
4. Is there option to combine multiple cards in a row?

**Comment by jaclynadams** [comment]
Should I mock up cards for all of these tags plus demand and wind speed? So there would be 8 cards total?

**Comment by jaclynadams** [comment]
Added 4 example cards. New ones can easily be added on dashboard page.
