### ISSUE TITLE
Bar chart legend needs to update on tag change

### ISSUE THREAD

**Issue by amadeuspzs** [DecodedCo/predix-seed-xlp#8]
![image](https://cloud.githubusercontent.com/assets/534681/19082840/d010e7c4-8a2d-11e6-83b3-46f0d0675d71.png)

**Comment by amadeuspzs** [comment]
While wind power is displayed, legend on top left and top right showing CoalPower

**Comment by jaclynadams** [comment]
Based on my discussions with the PX team, not sure that it is possible with this component to have a dynamic legend... Going to play around with that a little more after everything else.

**Comment by jaclynadams** [comment]
Was able to fix it by grabbing the Highcharts object within the PX element, yay!
