### ISSUE TITLE
Split out timeseries line and bar charts as separate cards

### ISSUE THREAD

**Issue by amadeuspzs** [DecodedCo/predix-seed-xlp#9]
![image](https://cloud.githubusercontent.com/assets/534681/19082988/5e4e88c0-8a2e-11e6-930d-682cd78d9d93.png)

Can we have two timeseries html files - one for bar chart and one for line chart?

**Comment by jaclynadams** [comment]
I figured they would only use one or the other in which case they can just comment out the chart in the card? 
If you think its easier to just do them separately I can replicate the entire card and change that one aspect.

**Comment by amadeuspzs** [comment]
I think having two cards and letting them choose would be easier for the students.

Something like:

![image](https://cloud.githubusercontent.com/assets/534681/19112677/34adbc88-8ad4-11e6-9307-77bb02217755.png)

**Comment by jaclynadams** [comment]
I added a tag to the time series card that allows them to show one card or the other and then made two instances of the card in the dashboard. Can't bring myself to copy-paste that much code!
